services:
  servidor-bd:
    image: mysql:8.0
    container_name: servidor-bd-ejemplo
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "sre_db"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sre-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 20

  app-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-backend
    restart: unless-stopped
    environment:
      DB_HOST: servidor-bd
      DB_USER: root
      DB_PASSWORD: "123456"
      DB_NAME: sre_db
    depends_on:
      servidor-bd:
        condition: service_healthy
    expose:
      - "5000"
    networks:
      - sre-network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - sre-network

networks:
  sre-network:
    driver: bridge

volumes:
  mysql_data:
  npm_data:
  npm_letsencrypt:
